Repository MrB141107/Python_Projects, pull requests merged in 2023-10, with the labels that each got.

#11 Added Hangman Game
  hangman_game.py
Labels: good first issue, hacktoberfest-accepted

#15 Created A New Minigame
  rock_paper,,scissor.py
Labels: enhancement, good first issue

#14 A python app that encrypts and manages your passwords
  password_manager.py
Labels: enhancement, good first issue, valid

#24 Created depth_first_search.py
  depth_first_search.py
Labels: hacktoberfest-accepted, valid

#31 Create Currency Converter
  currencyConverter.py
Labels: enhancement, hacktoberfest-accepted, valid, awesome, python

#32 Added An automated mailing app
  Mailer-main/Mailer-main/LICENSE
  Mailer-main/Mailer-main/Logo.png
  Mailer-main/Mailer-main/README.md
  Mailer-main/Mailer-main/User.py
  Mailer-main/Mailer-main/logo-color.ico
  Mailer-main/Mailer-main/mail_read.py
  Mailer-main/Mailer-main/mail_send.py
  Mailer-main/Mailer-main/main.py
  Mailer-main/Mailer-main/setup_repair.py
Labels: enhancement, python

#61 Added snake game using pygame.
  snake_game/__pycache__/constants.cpython-38.pyc
  snake_game/constants.py
  snake_game/images/game_logo.jpg
  snake_game/requirement.txt
  snake_game/snake_game.py
Labels: help wanted, question

#68 Created ToDo.py
  ToDo.py
Labels: good first issue, hacktoberfest-accepted, valid, awesome, python
